export const GET_DATA_REQUEST ="GET_DATA_REQUEST"
export const GET_DATA_SUCCESS ="GET_DATA_SUCCESS"
export const GET_DATA_FAILED ="GET_DATA_FAILED"

export const GET_ONEDATA_REQUEST ="GET_ONEDATA_REQUEST"
export const GET_ONEDATA_SUCCESS ="GET_ONEDATA_SUCCESS"
export const GET_ONEDATA_FAILED ="GET_ONEDATA_FAILED"

export const GET_PROFILEDITAILS_REQUEST ="GET_DATA_REQUEST"
export const GET_PROFILEDITAILS_SUCCESS ="GET_DATA_SUCCESS"
export const GET_PROFILEDITAILS_FAILED ="GET_DATA_FAILED"

export const POST_LOGIN_DATA_REQUEST="POST_LOGIN_DATA_REQUEST"
export const POST_LOGIN_DATA_SUCCESS="POST_LOGIN_DATA_SUCCESS"
export const POST_LOGIN_DATA_FAILED="POST_LOGIN_DATA_FAILED"

export const POST_SIGNUP_REQUEST="POST_SIGNUP_REQUEST"
export const POST_SIGNUP_SUCCESS="POST_SIGNUP_SUCCESS"
export const POST_SIGNUP_FAILED="POST_SIGNUP_FAILED"

export const POST_ORDERS_REQUEST="POST_ORDERS_REQUEST"
export const POST_ORDERS_SUCCESS="POST_ORDERS_SUCCESS"
export const POST_ORDERS_FAILED="POST_ORDERS_FAILED"


export const REMOVE_BASKET_PRUDOCT ="REMOVE_BASKET_PRUDOCT"